import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,Gem,ScanLine,Shirt} from 'lucide-react';
import {products} from '@/lib/products';
import {ProductCard} from '@/components/store';

export default function Home(){return <main>
<section className="hero"><Image src="https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1800&q=90" fill priority sizes="100vw" alt="Tuscara outerwear campaign placeholder"/><div className="veil"/><div className="heroCopy"><small>TUSCARA LONDON<br/>NEW COLLECTION</small><h1>MODERN<br/>CLOTHING<br/>FOR REAL<br/>PEOPLE.</h1><p>Premium outerwear and everyday pieces designed with a focus on silhouette, comfort and understated style.</p><div><Link className="light" href="/shop">SHOP COLLECTION <ArrowRight/></Link><Link className="outline" href="/lookbook">EXPLORE LOOKBOOK</Link></div></div><div className="heroFoot"><span>01 / 03</span><i/><span>SCROLL TO EXPLORE</span></div></section>
<section className="triptych"><article className="campaign women"><Image src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=88" fill sizes="33vw" alt="Tuscara women campaign placeholder"/><div/><span><h2>OUR<br/>COLLECTION</h2><p>Premium jackets designed for everyday confidence.</p><Link href="/shop">SHOP ALL →</Link></span></article><section className="best"><h2>BEST SELLERS</h2><p>Most loved pieces from our latest collection.</p><div>{products.map(p=><ProductCard key={p.slug} p={p}/>)}</div></section><article className="campaign men"><Image src="https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1200&q=88" fill sizes="33vw" alt="Tuscara mens campaign placeholder"/><div/><span><small>TUSCARA LONDON</small><h2>CRAFTED<br/>FOR EVERYDAY<br/>MOMENTS.</h2><p>Clean designs, thoughtful details and premium materials.</p><Link href="/about">READ OUR STORY →</Link></span></article></section>
<section className="look"><div><small>LOOKBOOK</small><h2>REAL PEOPLE.<br/>REAL STYLE.</h2><Link href="/lookbook">VIEW LOOKBOOK →</Link></div><figure><Image src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=88" fill sizes="70vw" alt="Tuscara lookbook placeholder"/></figure></section>
<section className="benefits"><div><Gem/><b>PREMIUM MATERIALS</b><span>Selected for quality and durability.</span></div><div><ScanLine/><b>TIMELESS DESIGNS</b><span>Style that stays relevant.</span></div><div><Shirt/><b>MADE FOR EVERYDAY</b><span>Comfort meets confidence.</span></div></section>
<footer><div className="footLogo"><b>T U S C A R A</b><span>L O N D O N</span></div><div className="footGrid"><div><b>SHOP</b><Link href="/shop">All Products</Link><Link href="/shop">New Arrivals</Link><Link href="/shop">Men</Link><Link href="/shop">Women</Link></div><div><b>SUPPORT</b><a>Shipping</a><a>Returns</a><a>Size Guide</a><a>Contact</a></div><div><b>ABOUT</b><Link href="/about">Our Story</Link><Link href="/lookbook">Lookbook</Link><a>Journal</a></div><div><b>JOIN THE TUSCARA JOURNAL</b><p>New collections, campaign stories and private releases.</p><label><input placeholder="Enter your email"/><button>→</button></label></div></div><div className="copy">© 2026 Tuscara London <span>Privacy · Terms · Cookies</span></div></footer>
</main>}